# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-12 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UltimaRequisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_path', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=255)),
                ('http_host', models.TextField()),
            ],
        ),
    ]
