# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-07 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_membro', models.IntegerField()),
                ('id_lattes', models.TextField()),
                ('nome_inicial', models.TextField()),
                ('nome_lattes', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Membros',
            },
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('autores', models.TextField(blank=True, null=True)),
                ('titulo', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-ano', 'titulo'],
                'verbose_name_plural': 'Producoes',
            },
        ),
        migrations.CreateModel(
            name='ApresentacaoDeTrabalho',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
                ('natureza', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Apresentacoes de Trabalhos',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='ArtigoAceito',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
                ('revista', models.TextField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                ('numero', models.TextField(blank=True, null=True)),
                ('paginas', models.TextField(blank=True, null=True)),
                ('doi', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Artigos Aceitos',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='ArtigoEmPeriodico',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
                ('revista', models.TextField(blank=True, null=True)),
                ('issn', models.TextField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                ('numero', models.TextField(blank=True, null=True)),
                ('paginas', models.TextField(blank=True, null=True)),
                ('doi', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Artigos em Periodicos',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='CapituloDeLivroPublicado',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
                ('livro', models.TextField(blank=True, null=True)),
                ('edicao', models.TextField(blank=True, null=True)),
                ('editora', models.TextField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                ('paginas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Capitulos de Livro Publicados',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='DesenhoIndustrial',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
                ('pais', models.TextField(blank=True, null=True)),
                ('tipo_patente', models.TextField(blank=True, null=True)),
                ('numero_registro', models.TextField(blank=True, null=True)),
                ('data_deposito', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Desenhos Industriais',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='LivroPublicado',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
                ('edicao', models.TextField(blank=True, null=True)),
                ('editora', models.TextField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                ('paginas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Livros Publicados',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='OutroTipoDeProducaoBibliografica',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
                ('natureza', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Outros Tipos de Producao Bibliografica',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='OutroTipoDeProducaoTecnica',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
                ('natureza', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Outros Tipos de Producao Tecnica',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='Patente',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
                ('pais', models.TextField(blank=True, null=True)),
                ('tipo_patente', models.TextField(blank=True, null=True)),
                ('numero_registro', models.TextField(blank=True, null=True)),
                ('data_deposito', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Patentes',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='ProcessoOuTecnica',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
                ('natureza', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Processos ou Tecnicas',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='ProducaoArtistica',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
            ],
            options={
                'verbose_name_plural': 'Producoes Artisticas',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='ProdutoTecnologico',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
            ],
            options={
                'verbose_name_plural': 'Produtos Tecnologicos',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='ProgramaComputador',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
                ('pais', models.TextField(blank=True, null=True)),
                ('tipo_patente', models.TextField(blank=True, null=True)),
                ('numero_registro', models.TextField(blank=True, null=True)),
                ('data_deposito', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Programas de Computador',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='ResumoEmCongresso',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
                ('nomeDoEvento', models.TextField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                ('numero', models.TextField(blank=True, null=True)),
                ('paginas', models.TextField(blank=True, null=True)),
                ('doi', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Resumos em Congresso',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='ResumoExpandidoEmCongresso',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
                ('nomeDoEvento', models.TextField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                ('paginas', models.TextField(blank=True, null=True)),
                ('doi', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Resumos Expandidos em Congresso',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='SoftwareComPatente',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
            ],
            options={
                'verbose_name_plural': 'Softwares com Patente',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='SoftwareSemPatente',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
            ],
            options={
                'verbose_name_plural': 'Softwares sem Patente',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='TextoEmJornalDeNoticia',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
                ('nomeJornal', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                ('paginas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Textos em Jornais de Noticia',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='TrabalhoCompletoEmCongresso',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
                ('nomeDoEvento', models.TextField(blank=True, null=True)),
                ('volume', models.TextField(blank=True, null=True)),
                ('paginas', models.TextField(blank=True, null=True)),
                ('doi', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Trabalhos Completos em Congresso',
            },
            bases=('curriculo.producao',),
        ),
        migrations.CreateModel(
            name='TrabalhoTecnico',
            fields=[
                ('producao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='curriculo.Producao')),
            ],
            options={
                'verbose_name_plural': 'Trabalhos Tecnicos',
            },
            bases=('curriculo.producao',),
        ),
        migrations.AddField(
            model_name='producao',
            name='membros',
            field=models.ManyToManyField(to='curriculo.Membro'),
        ),
    ]
